language: rust
cache: cargo
rust:
  - stable
  - nightly

os:
  - linux

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - secure: "VdWpdGMMMGuQT66mgvpSvlW1Dv4mbn16UoFZ0QzgDQUkLrSArT4qExxe6piRK2avOjGbMyhP0wGnMZvrVkZXub2KsbnOqpSQUTNHiJnl0ooSAyC/ASuBYUEJNFQoBIscjmSgv21Y8Lu3uO3jF80NERpFsI/lSLRDpGKjmmx7xrDFjOm/FVwTr6Nw9sxGZtKxXxmAgz+kJGtAc3n3VOH+PyOtbwJtdx4+6Hwy3JCJcMRSwYh35AptU3kP+NkO7jiBNi5blxs3obBwKyI88tmrJeJe9c9Yp6OdQGYiJk8bkEUsZKVw7P8QHE+b+um0HUw0XzqGkMax9ihysaBd+nPR1aWWVHDNVLlt0rvIhK0v9O4lOnvMR0KENbCUhdL2X4KwHhQEv20LqytMOyhce4aBrJ/4bBi7pwxkopiZwsHZ9NOXFBYGfo4Kl7ZH1cfs66L+8lGMOQWs/JpTeE3wo5b39Ky0mH/BIoPtZUPDRvp3SRrZ3CDkoQ6KWNDXY3ebOcW0o0STTkC8Wjbbaexp8z0NkFXlVbRsXOVG1Idi77VjwRFLbJKolV0fgXBanWM5IY4ry0dj5Ho8z7dSVJbISkhZvDVa/a/9jmV8eVylJOjxo1kX6d/Mh6rwT5UcP1sb6CRl/L+mYuq0MekDlT9HP/FKeyML/cvklDO6DBKAa9lsWwE="

notifications:
  email:
    on_success: never

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:duggan/bats --yes; fi
   - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; else brew update; fi
   - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libusb-1.0-0-dev bats; else brew install libusb bats; fi

before_script:
  - export PATH="$PATH":~/.cargo/bin

script:
  # Install Janus
  - curl -sL https://raw.githubusercontent.com/ethereumproject/janus/master/get.sh | bash
  # Add Janus to PATH.
  - export PATH=$PATH:$PWD/janusbin
  - export APP_VERSION="$(janus version -format 'TAG_OR_NIGHTLY')"
  - export RUST_BACKTRACE=1
  - cargo test --all --verbose
  - cargo build --all --verbose --release
  - cp ./target/release/emerald-vault "$HOME/.cargo/bin/"
  - cp ./target/release/emerald-vault "./target/release/emerald"
  - bats cli.bats

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
  tags: true
