[package]
name = "webchain-cli"
version = "0.22.0"
authors = ["Webchain Network"]
description = "Console utility for secure account management"
homepage = "https://webchain.network"
repository = "https://github.com/webchain-network/webchain-cli"
documentation = "https://docs.rs/emerald-cli"
keywords = ["webchain-network", "blockchain", "crypto-wallet", "cold-storage", "cli"]
categories = ["console", "bash"]
readme = "README.md"
license = "Apache-2.0"


[[bin]]
name = "webchain-cli"
path = "src/main.rs"

[dependencies]
log = "0.3"
jsonrpc-core = "7.1.1"
serde = "1.0"
hex = "0.2"
lazy_static = "0.2"
serde_json = "1.0"
serde_derive = "1.0"
webchain-rs = { git = "https://github.com/webchain-network/webchain-rs" }
regex = "0.2"
rustc-serialize = "0.3"
hyper = "0.10"
reqwest = "0.6"
rpassword = "1.0"
url = "1.7.0"
text_io = "0.1"
clap = {version = "2.31", features = ["yaml", "color"]}
env_logger = { version = "0.4", optional = true }
clippy = {version = "0.0", optional = true}

[dev-dependencies]
tempdir = "0.3"
quickcheck = "0.4"
# quickcheck_macros = "0.4"

[features]
default = ["cli"]
cli = ["env_logger"]
dev = ["clippy"]
